---
# Configuration — deploy SSH server/client configs, banner, and manage service.

- name: OpenSSH | configure | Deploy SSH server configuration
  become: true
  ansible.builtin.template:
    src: "ssh/sshd_config.j2"
    dest: "{{ openssh_sshd_config_path }}"
    owner: root
    group: root
    mode: '0600'
    backup: true
    validate: "{{ openssh_sshd_validate_command | default('/usr/sbin/sshd -t -f %s') }}"
  notify: restart openssh

- name: OpenSSH | configure | Deploy SSH client configuration
  become: true
  ansible.builtin.template:
    src: "ssh/ssh_config.j2"
    dest: "{{ openssh_ssh_config_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  when: >
    openssh_configure_client | bool

- name: OpenSSH | configure | Create banner file
  become: true
  ansible.builtin.template:
    src: "ssh/banner.j2"
    dest: "{{ openssh_banner_path }}"
    owner: root
    group: root
    mode: '0644'

- name: OpenSSH | configure | Ensure SSH service is enabled
  become: true
  ansible.builtin.service:
    name: "{{ openssh_service_name }}"
    enabled: true
    state: started
  when: >
    openssh_service_enabled | bool

- name: OpenSSH | configure | Ensure SSH service is disabled
  become: true
  ansible.builtin.service:
    name: "{{ openssh_service_name }}"
    enabled: false
    state: stopped
  when: >
    not openssh_service_enabled | bool and openssh_allow_service_stop | bool and (ansible_connection != 'ssh')
