---
# =============================================================================
# Ansible Role: OpenSSH - Handlers
# =============================================================================
# Service management handlers triggered by tasks.
# =============================================================================

- name: OpenSSH | handlers | Restart OpenSSH service
  become: true
  ansible.builtin.service:
    name: "{{ openssh_service_name }}"
    state: restarted
  when: openssh_service_enabled | bool
  listen: "restart openssh"
