---
# =============================================================================
# Ansible Role: OpenSSH - Handlers
# =============================================================================
# Handlers are used to perform service actions in response to configuration changes.
# This handler manages OpenSSH service state when notified by tasks that modify
# system configuration.
#
# Variables:
#   openssh_service_name - Name of the OpenSSH service to manage (ssh/sshd)
#   openssh_service_enabled - Boolean flag to control service enablement
#
# Handler Triggers:
#   restart openssh - Triggered when OpenSSH configuration changes
# =============================================================================

# -----------------------------------------------------------------------------
# 1. OpenSSH Service Restart
# -----------------------------------------------------------------------------
- name: 🔄 OpenSSH | handlers | Restart OpenSSH service
  become: true
  ansible.builtin.systemd:
    name: "{{ openssh_service_name }}"
    state: restarted
    enabled: "{{ openssh_service_enabled }}"
  listen: "restart openssh"
